/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GameStarterUI.java
 *
 * Created on Oct 21, 2009, 8:53:41 AM
 */

package monopoly;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author mike
 */
public class GameStarterUI extends javax.swing.JFrame {
    private Game game_;
    private int startX = 10;
    private int startY = 10;
    private Color color_ = Color.magenta;
    
    /** Creates new form GameStarterUI */
    public GameStarterUI (Game game) {
        initComponents();
        this.setVisible(true);
        game_ = game;
        chooseColor.setBackground(color_);
    }

    @Override
    public void paint(Graphics g) {

        
        int rowGap = 15, colGap = 20;
        int y = startY+rowGap;
        for (Player player : Game.getPlayers()) {
            g.setColor(Color.BLACK);
            g.drawString(player.getName(), startX, y);
            g.setColor(player.getColor());
            g.fillRect(startX+colGap, y, 100, 20);            
            y += rowGap;
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        joinGame = new javax.swing.JButton();
        chooseColor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameLabel.setText("Name :");

        joinGame.setText("Join Game");
        joinGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinGame(evt);
            }
        });

        chooseColor.setText("color");
        chooseColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setPlayerColor(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(nameLabel)
                .addGap(18, 18, 18)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chooseColor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(joinGame)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(joinGame)
                    .addComponent(chooseColor))
                .addContainerGap(254, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setPlayerColor(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setPlayerColor
        // TODO add your handling code here:
        color_ = JColorChooser.showDialog(this, "Choose the color", Color.yellow);
        chooseColor.setBackground(color_);
    }//GEN-LAST:event_setPlayerColor

    private void joinGame(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinGame
        // TODO add your handling code here:
        for (Player player : Game.getPlayers()) {
            if (player.getName().equals(name.getText())) {
                JOptionPane.showMessageDialog(this, "Player name cannot be duplicated");
                return;
            }
            if (player.getColor().equals(color_)) {
                JOptionPane.showMessageDialog(this, "Player color cannot be duplicated");
                return;
            }
        }
        this.dispose();
        Game.gameUI = new GameUI();
        Game.thread.start();
        Game.thread.sendMessage("p|"+name.getText()+"|"+String.valueOf(color_.getRGB()));        
    }//GEN-LAST:event_joinGame

    /**
    * @param args the command line arguments
    */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GameStarterUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseColor;
    private javax.swing.JButton joinGame;
    private javax.swing.JTextField name;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables

}
